spring:
  kafka:
    #Kafka服务器地址
    bootstrap-servers: blade04.soaringlab.top:9092
    consumer:
      #设置数据value的反序列化处理类
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    # h2
    url: jdbc:h2:file:./camunda-h2-database
#
#  datasource:
#    url: jdbc:mysql://47.100.121.32:3306/camunda?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&nullCatalogMeansCurrent=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456a
camunda.bpm.admin-user:
  id: admin
  password: 123456
camunda:
  bpm:
    auto-deployment-enabled: true
    history-level: audit
    authorization:
      tenant-check-enabled: true
    default-number-of-retries: 4


server:
  port: 10006